
version: '3.9'

services:
  
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: 
      - .env 
    ports:
      - "443:443"
    networks:
      - transcendance_network
    restart: on-failure
    # depends_on:
    #   - django
    #   - frontend
    volumes:
      - dist:/var/www/html/dist/
    
#   django:
#     container_name: django
#     build:
#       context: requirements/django
#       dockerfile: Dockerfile
#     env_file: 
#       - .env 
#     expose:
#       - "443"
#     networks:
#       - transcendance_network
#     restart: on-failure
#     depends_on:
#       - database
#     volumes:
#       - ./django:/django


#   database:
#     container_name : database
#     env_file: 
#       - .env  
#     expose:
#       - "5432"
#     networks:
#       - transcendance_network
#     restart: on-failure
#     volumes:
#       - database:/var/lib/postgresql/data/
  
  
  
#   frontend:
#     container_name : frontend
#     build:
#       context: requirements/frontend
#       dockerfile: Dockerfile
#     volumes:
#       - dist:/app/dist
#       - ./frontend:/app
#     restart: on-failure



networks:
  transcendance_network:
    driver: bridge

volumes:
  dist:
