FROM python:3.12.1-slim-bullseye


# WORKDIR /django/
# # for postgresql
# RUN apt-get update && apt-get install -y libpq-dev postgresql-client gcc openssl netcat

# COPY tools/docker-entrypoint.sh /docker-entrypoint.sh
# COPY requirements.txt /game/requirements.txt

# COPY requirements.txt /game/    
# RUN pip install -r requirements.txt;


# EXPOSE 443

# CMD ["/docker-entrypoint.sh"]
